name: Durango FTP dev mode

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  winrt-build:
    runs-on: windows-latest

    env:
      SolutionPath: UniversalFtpServer.sln
      Platform: x64
      Configuration: Release
      AppxBundle: Never
      PackageOutputRootDir: UniversalFtpServer

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.0.2
        
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash
        
    - name: Generate Self-Signed Certificate
      id: generate_cert
      run: |
       $cert = New-SelfSignedCertificate -CertStoreLocation "Cert:\CurrentUser\My" -Subject "CN=MyUWPCert" -KeyAlgorithm RSA -KeyLength 2048 -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider" -KeyExportPolicy Exportable -NotAfter (Get-Date).AddYears(1) -Type CodeSigningCert
       echo "THUMBPRINT=$($cert.Thumbprint)" >> $env:GITHUB_ENV
      shell: pwsh

    - name: App Build
      run: |
       msbuild /restore `
       "$env:SolutionPath" `
       /p:Platform=$env:Platform `
       /p:Configuration=$env:Configuration `
       /p:UapAppxPackageBuildMode=$env:BuildMode `
       /p:AppxBundle=$env:AppxBundle `
       /p:PackageCertificateThumbprint="${{ env.THUMBPRINT }}" `
       /p:AppxPackageTestDir="${{ env.PackageOutputRootDir }}\${{ env.PACKAGE_NAME }}" `
       /p:RestorePackagesConfig=true
      shell: pwsh

    - name: Clean the Package
      run: |
        $PackagePath = "${{ env.PackageOutputRootDir }}"
        if (Test-Path $PackagePath) {
          Write-Host "Cleaning package directory: $PackagePath"
          Remove-Item -Recurse -path "$PackagePath\Add-AppDevPackage.resources" -ErrorAction SilentlyContinue
          Remove-Item -Recurse -path "$PackagePath\TelemetryDependencies" -ErrorAction SilentlyContinue
          Remove-Item -Recurse -path "$PackagePath\Dependencies\arm" -ErrorAction SilentlyContinue
          Remove-Item -Recurse -path "$PackagePath\Dependencies\arm64" -ErrorAction SilentlyContinue
          Remove-Item -Recurse -path "$PackagePath\Dependencies\x86" -ErrorAction SilentlyContinue
          Remove-Item -Recurse -path "$PackagePath\Dependencies\Win32" -ErrorAction SilentlyContinue
          Remove-Item -path "$PackagePath\Add-AppDevPackage.ps1" -ErrorAction SilentlyContinue
          Remove-Item -Recurse -path "$PackagePath\Install.ps1" -ErrorAction SilentlyContinue
        } else {
          Write-Host "Package path does not exist: $PackagePath"
          exit 1
        }
      shell: powershell

    - name: Create Archive
      run: |
        $PackagePath = "${{ env.PackageOutputRootDir }}"
        if (Test-Path $PackagePath) {
          Write-Host "Creating archive for: $PackagePath"
          Compress-Archive -Path "$PackagePath\*" -DestinationPath "${{ env.PackageOutputRootDir }}\DURANGO-FTP-Release.zip"
          Write-Host "Contents of package output directory after archiving:"
          Get-ChildItem -Path "${{ env.PackageOutputRootDir }}" -Recurse
        } else {
          Write-Host "Package path does not exist for archiving: $PackagePath"
          exit 1
        }
      shell: powershell

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: DURANGO-FTP-Release
        path: ${{ env.PackageOutputRootDir }}\DURANGO-FTP-Release.zip
